[debian-13-x86-64]
arch = "x86-64"
os = { type = "linux", linux = "debian", debian = 13 }
image = { type = "qcow2", url = "https://cloud.debian.org/images/cloud/trixie/latest/debian-13-generic-amd64.qcow2" }
hash = { type = "sha512sums", url = "https://cloud.debian.org/images/cloud/trixie/latest/SHA512SUMS" }
kernel_root = "/dev/vda1"
user = "debian"

[arch-x86-64]
arch = "x86-64"
os = { type = "linux", linux = "arch" }
image = { type = "qcow2", url = "https://fastly.mirror.pkgbuild.com/images/latest/Arch-Linux-x86_64-cloudimg.qcow2" }
hash = { type = "sha256sums", url = "https://fastly.mirror.pkgbuild.com/images/latest/Arch-Linux-x86_64-cloudimg.qcow2.SHA256" }
kernel_root = "/dev/vda3"
user = "arch"
