[package]
name = "lusid-system"
version = "0.1.0"
edition = "2024"

[dependencies]
etc-os-release = "0.1.1"
hostname = "0.4.1"
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
serde_json = "1"
